### ISSUE TITLE
Enchancement Request: New logo and improve UX

### ISSUE THREAD

**Issue by nipuna777** [gaining/Resetter#1]
I saw this application featured on OMGUbuntu and I really like the simplicity and functionality it offers. I remember personally needing this functionality more than once when playing around with Ubuntu. 

I feel that the logo design and the interface could be a bit improved. I'm a developer myself but I'm trying to learn UX. Would you like to work on a new logo and possibly some redesigns on the screens with me? I don't claim to be an expert but we can work on improving the UI/UX a bit on the application?

**Comment by gaining** [comment]
Yes, that was definitely on my todo list to get a new logo and I'm completely open to suggestions.

**Comment by gaining** [comment]
fixed in 49f9212

**Comment by gaining** [comment]
New logo should definitely solve this issue
