### ISSUE TITLE
mainfest and user list not found / os name lubuntu Ubuntu 20.10 groovy

### ISSUE THREAD

**Issue by golam71** [gaining/Resetter#113]
*Issue title

*Linux Distro and version

*Version of Resetter

*Description of Issue

*Content of log file located in /var/log/resetter/resetter.log if applicable

**Comment by tonywateround** [comment]
Just download the default .manifest file of your system here:

http://old-releases.ubuntu.com/releases/X/ubuntu-Y-desktop-amd64.manifest

Change X with your system version and Y with system subversion.

For Ubuntu desktop 20.04.2, the default manifest file is:
http://old-releases.ubuntu.com/releases/20.04/ubuntu-20.04.2-desktop-amd64.manifest
