### ISSUE TITLE
Better multithreading/threading support

### ISSUE THREAD

**Issue by gaining** [gaining/Resetter#14]
The progress bar and throbber animations hangs although the program is doing its job. That is because they are both running on the main ui thread. This, in fact, causes the ui to become unresponsive.

**Comment by gaining** [comment]
I managed to get better multithreading/threading support on the app. It no longer hangs or freezes on long processes. This will be implemented in the next release along with other features requests opened here.

**Comment by franchesoni** [comment]
I think I may have the same issue, I have been waiting for more than an hour and the cleaning up progress bar doesn't seem to start moving. Should I cancel the process?

**Comment by gaining** [comment]
Yes, and the issue you're having has nothing to do with multithreading but you're welcome to open a new issue detailing the problem that you're having.
