### ISSUE TITLE
Custom reset removed apps that were specifically unchecked

### ISSUE THREAD

**Issue by mezpahlan** [gaining/Resetter#18]
I chose a custom reset as I wanted to preserve some of my apps such as Synaptic for example. These were removed, however, after the process completed.

Not a massive issue as I can install them again, but it seems to have removed all rather than the custom set I specified.

This is on the first screen for the custom reset option where it suggests that you remove everything as they are not present in a vanilla build.

**Comment by mezpahlan** [comment]
Ok hang about...... I think I may have an idea on what's going on. When I re-installed an application that I had unchecked but found missing after the reset process, Variety, I noticed that it also installed a load of dependencies with it. I recognised those dependency package names as ones I had *not* unchecked.

So perhaps I spoke too early. 

Perhaps a quick run through the dependencies could be performed and then grouped under the top level packages so it is easier to see what other packages need to be unchecked when you uncheck your favourite package prior to starting the process?

**Comment by gaining** [comment]
Thanks for your report. 
This seems logical enough. To make things clearer, I will create a dependency check function that will show users which extra packages(dependencies) will be removed or dealt with after checking a specific package for removal. If that dependency is on the *packages to remove* list, it will let users know.
