### ISSUE TITLE
struck in /dev/sda4 : clean

### ISSUE THREAD

**Issue by gaopeng-eugene** [gaining/Resetter#20]
Hello
My Lenovo computer install Ubuntu and Windows 10. After using your app, ubuntu will strcu in /dev/sda3 :clean. Recovery mode is OK.
Can you tell me how to solve the problem?

Best Wishes

**Comment by gaining** [comment]
Just so I understand what you're saying, I'm guessing that you mean you're dual booting Ubuntu and windows 10. You reset Ubuntu and something happened in /dev/sda4 or 3? Can you elaborate on that? Also which Ubuntu version are you using and which reset option did you choose.

A quick search to what I think you're asking lead me to this page: https://askubuntu.com/questions/809648/booting-problem-after-upgrade-dev-sda2-clean. According to this, you're not having any issues, if you are, please elaborate.

**Comment by gaining** [comment]
No input from user closing
