### ISSUE TITLE
support for deepin v 15.4.1

### ISSUE THREAD

**Issue by elswerky** [gaining/Resetter#23]
i installed version resetter (0.3.7-rc on deepin v 15.4.1 and it opened  but have'n't tested it yet 

#but 
when i installed v 1 stable on deepin 15.4.1 it didn't open and said thet deepin 15.4.1 not supported yet

**Comment by gaining** [comment]
Yeah, I'm working on a new version that'll be updated to be compatible with the new operating systems + other new features. It should be released sometime this weekend.

**Comment by gaining** [comment]
Update: Will realease the next stable version tomorrow.

**Comment by elswerky** [comment]
thanks for informing me
 i puplished this information in deepin group on telegram

2017-07-31 4:58 GMT+02:00 gaining <notifications@github.com>:

**Comment by gaining** [comment]
You're welcome.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
