### ISSUE TITLE
userlist could not be found, features requiring this file will now work

### ISSUE THREAD

**Issue by marcosmontivero** [gaining/Resetter#25]
Hi, i tried to reset my linux mint 17.3 but nothing happened. 

This message is shown when I open the app.

**Comment by marcosmontivero** [comment]
marc@Marcos-LinuxMint ~ $ sudo resetter
[sudo] password for marc: 
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 
^CTraceback (most recent call last):
  File "/usr/lib/resetter/Resetter.py", line 514, in <module>
    window = UiMainWindow()
  File "/usr/lib/resetter/Resetter.py", line 28, in __init__
    self.d_env = Settings()
  File "/usr/lib/resetter/SetEnvironment.py", line 52, in __init__
    self.filesExist(self.manifest, self.userlist)
  File "/usr/lib/resetter/SetEnvironment.py", line 191, in filesExist
    self.error_msg.exec_()

**Comment by gaining** [comment]
Thanks for reporting this error. I'll have a look.

**Comment by gaining** [comment]
It's a file naming error, I'll push a fix tonight for this issue.

**Comment by gaining** [comment]
fixed in 98982ac
