### ISSUE TITLE
work on debian ?

### ISSUE THREAD

**Issue by jemadux** [gaining/Resetter#29]
hm , will that support sometime debian? cuz i would like resset my debian  as was in first time

**Comment by jemadux** [comment]
thank you so much

**Comment by gaining** [comment]
@jemadux Which debian version would you say is the most popular? cinnamon, gnome, xfce, kde, etc... And which one are you using?

**Comment by jemadux** [comment]
debian is one ..  depends about the user about it's needs . desktop envimoremt / window manager is about the choice of user during the installation . the main problem is about which branch  they use . most people use testing branch or unstable branch . 

i have a laptop that it's coveriable so i am using debian gnome with testing  with some repos of unstable branch

**Comment by gaining** [comment]
OK thanks.

**Comment by gaining** [comment]
I did not have much time to work on it this weekend due to work and school. Also after further testing, I realized it's just not ready. But it won't be too long at this point.

**Comment by AllAboutThatTEC** [comment]
Hello, I am currently running Debian stretch with gnome. I was wondering what the status is of a Debian compatible version is. Thanks in advance!

**Comment by gaining** [comment]
Definitely early November Anytime before November 15th. Really sorry for the wait.

**Comment by AllAboutThatTEC** [comment]
Cool I really appreciate it. I'm a hobbyist python programmer and I have a
debiam stretch machine, so if there's anything that I can help with let me
know, I'd be happy to!

**Comment by gaining** [comment]
Will be hosted at https://github.com/gaining/resetter-cli. 1st release tonight at 8:30pm EST

**Comment by gaining** [comment]
I wanted the both the cli version and GUI version to come out with the debian support at the same time. But with school exams, work and other life stuff I'm hardly finding any time to work on them both. So for now, the GUI version has initial Debian support.
