### ISSUE TITLE
default password does not work

### ISSUE THREAD

**Issue by jseyfferdt** [gaining/Resetter#3]
Hi,  I tried out the app many times, via the deb packages which works for ubuntu 16.10 also and everything runs smoothly except when using the default password NewLife3  it simply does not work.  Am I doing something wrong?

**Comment by gaining** [comment]
The default password is NewLife3!, somehow it striped out the !. I will fix it on the 3rd beta release

**Comment by jseyfferdt** [comment]
Thanks! Would you mind if i make some youtube tutorials about your app?

**Comment by gaining** [comment]
Not at all, just know that lots of things will change as more features and functions are added as I develop it. I fixed the password issue on the 3rd beta.
