### ISSUE TITLE
Ubuntu fresh install missing beautifulsoup4

### ISSUE THREAD

**Issue by maxgittelman** [gaining/Resetter#30]
Issue title
Fresh install missing beautifulsoup4

Linux Distro and version
Linux 16.04

Description of Issue
missing an install, I'm not sure if this can be included in the `apt` install somehow. Below what the issue:
```
maxgitt@mgpc:~/Downloads$ resetter
Traceback (most recent call last):
  File "/usr/lib/resetter/Resetter.py", line 22, in <module>
    from EasyRepo import EasyPPAInstall
  File "/usr/lib/resetter/EasyRepo.py", line 11, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
```

content of Log file located in /var/log/resetter/resetter.log
I was able to follow a stackoverflow reference [here]()

I simply needed to `pip install --upgrade beautifulsoup4` to fix the issue.

**Comment by gaining** [comment]
I'm guessing you're on ubuntu 16.04? Also, is beautiful soup missing before or after doing a reset?

**Comment by maxgittelman** [comment]
Yes Ubuntu 16.04, sorry I said Linux. beautiful soup is missing before a reset.

**Comment by gaining** [comment]
I think I understand what happened here. The recommended way to install resetter is through gdebi, because it will install all the dependencies required of it. I don't think you followed the recommended way and hence why you got that problem. Please check the #How to install section on the main page.
