### ISSUE TITLE
Resetter is already running

### ISSUE THREAD

**Issue by mdrost** [gaining/Resetter#33]
*Issue title: Resetter is already running

*Linux Distro and version: Ubuntu 17.04

*Version of Resetter: 1.0.3-stable

*Description of Issue
After killing application it cannot launch again and shows message `Resetter is already running`. Probably application should handle signals or shared memory should be better managed. 

*content of Log file located in /var/log/resetter/resetter.log
not needed

**Comment by gaining** [comment]
This happened because the way shared memory is current implemented is that it needs a clean exit to function properly. Since you killed it, it not clear the shared memory files properly but closing that window and opening it again will allow you to open the application properly again.
