### ISSUE TITLE
Stuck when removing vim-runtime

### ISSUE THREAD

**Issue by virgorasion** [gaining/Resetter#38]
## application stuck when removing
I got stuck when removing vim-runtime
im using ubuntu 17.04
can you fixed this ?

**Comment by virgorasion** [comment]
I got stuck when removing vim-runtime
im using ubuntu 17.04
can you fixed this ?

**Comment by gaining** [comment]
Hi, can you show me the content of your /var/log/resetter/resetter.log ? There's a pre-made template just for issues like this so  that I can troubleshoot better. Thanks.

**Comment by virgorasion** [comment]
i'm sorry, that my false.. your app is working well 👍
