### ISSUE TITLE
Support for mint 18.3

### ISSUE THREAD

**Issue by gaining** [gaining/Resetter#39]
Need to add support for mint 18.3

**Comment by dgertenbach** [comment]
How is this progressing?

**Comment by gaining** [comment]
Yeah, i'll be doing this today. I needed a new high capacity SSD to support all of my vms since my current one is basically full and it came in the mail 3 days ago.

**Comment by dgertenbach** [comment]
Thanks @gaining!

**Comment by gaining** [comment]
You're welcome, ran into some issues cloning my Linux partition, hence the delay.
