### ISSUE TITLE
Terminal version

### ISSUE THREAD

**Issue by aurimus** [gaining/Resetter#4]
Hi, my ubuntu is broken because of my actions. Can I use this while in root terminal on System Rescue?

**Comment by gaining** [comment]
Not yet, command line options are going to be added very soon. Most likely in the next few days.

**Comment by floreal797** [comment]
Waiting for this version... Is it implemented yet? Useful to reset a server, which has no graphical interface...

**Comment by gaining** [comment]
Yeah, it's being worked on gradually because I work on it maybe once every 2 weeks. Learning a new boring and complex library to build it and no donors support contributes to the slowness of the development. It's 60% complete though. :wink:

**Comment by gaining** [comment]
Now it's 90% complete. I might release it next week.

**Comment by floreal797** [comment]
Happy to read that, sounds good :)

**Comment by gaining** [comment]
https://github.com/gaining/resetter-cli, send all issues there. It will be the active repo this year
