### ISSUE TITLE
Error while run sudo resetter

### ISSUE THREAD

**Issue by gaurang7024** [gaining/Resetter#48]
$ sudo resetter 
 File "/usr/lib/resetter/Resetter.py", line 12, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so: undefined symbol: _ZN15QSessionManager16staticMetaObjectE

I have ubuntu 16.04

**Comment by gaining** [comment]
You must've not followed the proper install instructions since you're missing dependencies, please check: [the install instuctions](https://github.com/gaining/Resetter/blob/master/README.md#L6)
