### ISSUE TITLE
Hangs during reinstall on Ubuntu 16

### ISSUE THREAD

**Issue by nmgeek** [gaining/Resetter#49]
* Title
Hangs during reinstall on Ubuntu 16

*Linux Distro and version
Ubuntu 16

*Version of Resetter
2.2.0-stable

*Description of Issue
Hangs at start of Cleaning Up phase.  According to dpkg.log it is after it finished installing python-newt.  It seems to have uninstalled itself since 'resetter' is no longer in my path.  So I cannot try again without reinstalling.

Also, the error, QFile::seek: IODevice is not open, occurs regularly in my shell window.

*content of Log file located in /var/log/resetter/resetter.log
Does not exist.

**Comment by gaining** [comment]
Hey, thanks for reporting this issue. Which option did you use, auto or custom?

**Comment by nmgeek** [comment]
custom.  I think I used all the defaults but asked it to reinstall openssh-server when done.

**Comment by gaining** [comment]
Should be fixed in latest release provided that the correct manifest for distro is used.
