### ISSUE TITLE
Not working with ubuntu 18.04

### ISSUE THREAD

**Issue by bikramtuladhar** [gaining/Resetter#51]
*Stuck at File not found dialog box
*Linux Distro and version
Ubuntu 18.04
*Version of Resetter
resetter 2.2
*Description of Issue

*content of Log file located in /var/log/resetter/resetter.log

**Comment by gaining** [comment]
Ubuntu 18.04 won't be released until the 26th April. As this application greatly depends on a finished release of a distro, the manifest for it needs to be complete. I will never support a development version of  a distro other than the final release.
