### ISSUE TITLE
Error removing libllvm5.0

### ISSUE THREAD

**Issue by Wtfparadox** [gaining/Resetter#53]
Hey gaining, first of all thanks for making the resetter. Sadly I run into a problem when I try to run it. 

Ubuntu 16.04.4 LTS
Resetter 2.2.0

When I run the automatic reset option I get an error when the loader reaches 9%. The error is the following: Problems trying to remove: libllvm5.0:amd64 E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

This is the part of the log that I think is relevant, if you want more I can send you the whole log

[resetterlog.txt](https://github.com/gaining/Resetter/files/1884127/resetterlog.txt)

I have tried custom reset, disabling the removal of the package mentioned above. Then it proceeds to go to 23% and get stuck with the same error but for a different package: libdrm-common.

The part of the log for this error is added below.

[resetterlogerror2.txt](https://github.com/gaining/Resetter/files/1884843/resetterlogerror2.txt)

**Comment by gaining** [comment]
Make sure you're connected to the internet and run these commands:
apt update
dpkg --configure -a
apt install -fy
apt-get autoremove -y
apt-get clean

That's essentially what the cleaning phase does.

**Comment by riryl** [comment]
Having the same issue and tried above commands, still the same error. Thanks

**Comment by githubkido** [comment]
i try everything but its not happening
