### ISSUE TITLE
application won't open after installation

### ISSUE THREAD

**Issue by chakree10** [gaining/Resetter#54]
xhost:  unable to open display ":20"
Resetter.py: cannot connect to X server :20

this is the error i keep getting the more i try to install

**Comment by gaining** [comment]
Please use the pre-made template. No info on distro or version.

**Comment by ShashwatHiregoudar** [comment]
File "/usr/lib/resetter/Resetter.py", line 12, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so: undefined symbol: _ZN15QSessionManager16staticMetaObjectE

This is the error when i ran it in terminal
