### ISSUE TITLE
manifest and userlist can't be find

### ISSUE THREAD

**Issue by mehul009** [gaining/Resetter#55]
*Issue title
manifest and userlist cannot be found
*Linux Distro and version
ubuntu 18.04
*Version of Resetter
2.2.0
*Description of Issue
I want to reset my whole ubuntu because after updating it not working well so I open resetter but it gives me an error manifest could not be found if you have one then plz select and same for UserList also

*content of Log file located in /var/log/resetter/resetter.log
[resetter.log](https://github.com/gaining/Resetter/files/1951991/resetter.log)

**Comment by gaining** [comment]
I got school exams now, won't be updating it until I'm done with all my exams.
