### ISSUE TITLE
[SUGGESTION/IMPROVEMENT] dist-upgrade automated tool

### ISSUE THREAD

**Issue by jebeld17** [gaining/Resetter#56]
*[SUGGESTION/IMPROVEMENT] dist-upgrade automated tool

*Ubuntu (desktop) 17.10

*v1.1.2-Stable

*Suggestion for app improvement: Adding an automated 'dist-upgrade' tool for systems that are having problems seeing new OS distribution upgrades

*content of Log file located in /var/log/resetter/resetter.log not necessary

**Comment by gaining** [comment]
Version 1.1.2 no longer supported. This tool is tool is a reset tool with other functionalities that can help a reset. Upgrade tool is out of scope.
