### ISSUE TITLE
ImportError: /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so: undefined symbol: _ZN15QSessionManager16staticMetaObjectE

### ISSUE THREAD

**Issue by ShashwatHiregoudar** [gaining/Resetter#57]
*Issue title
Import Error
*Linux Distro and version
Linux Mint 18.1 cinamon
*Version of Resetter
2.2.0
*Description of Issue
Im getting this error what shall i do

*content of Log file located in /var/log/resetter/resetter.log
No such file

**Comment by gaining** [comment]
Your qt installation is utterly broken. Try to remove pyqt4 with sudo apt remove python-qt4 then reinstall it. If that doesn't work, you may have to do a full distro reset or just upgrade to Linux mint 18.3 then you can do a reset using resetter.
