### ISSUE TITLE
Resetter not rendering anything

### ISSUE THREAD

**Issue by kphillipsjr1101** [gaining/Resetter#63]
Nothing showing in application

Ubuntu 18.04LTS

Upon launching resetter I get a blank window with Ubuntu Resetter on the title bar with no option to do anything else. Icon on taskbar is also not loading properly (Getting the icon that indicates the app doesn't have an icon to use).

Nothing pushed to the .log file.

**Comment by gaining** [comment]
use the terminal and launch it by typing `sudo resetter`
