### ISSUE TITLE
could you add support for deepin 15.6?

### ISSUE THREAD

**Issue by chemel9** [gaining/Resetter#65]
the new deepin 15.6 , isn't supported by resetter
could you add support for deepin 15.6?

**Comment by gaining** [comment]
Sure, I tried to download the new version but as of 5:41am canada est time, deepins server are down. I'll try again another day when I got time or if anyone else wants to do it, they can just follow the tutorial on the main page to put deepin support by using resetter helper.

**Comment by chemel9** [comment]
you can download deepin here https://sourceforge.net/projects/deepin/files/15.6/
