### ISSUE TITLE
Ubuntu16.04 install error

### ISSUE THREAD

**Issue by zhhengcs** [gaining/Resetter#66]
*fail to install 

*4.15.0-29-generic #31~16.04.1-Ubuntu

*resetter_2.2.3-stable_all

*Error during install: 'Failed to fetch http://cn.archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_1.1.0~beta1ubuntu0.16.04.1_amd64.deb

**Comment by gaining** [comment]
Make sure that you have internet access, run `sudo apt update` then try to install again.
