### ISSUE TITLE
Resetter not functional on eOS Loki

### ISSUE THREAD

**Issue by ghost** [gaining/Resetter#67]
Resetter not functional on eOS Loki

Elementary OS Loki 0.4.1

Resetter 2.2.3-stable

Resetter does not open after installing (following [install instructions](https://github.com/gaining/Resetter/blob/master/README.md#how-to-install)), when running through the terminal with `sudo resetter` it responds with the following error:

```
Traceback (most recent call last):
  File "/usr/lib/resetter/Resetter.py", line 567, in <module>
    window = UiMainWindow()
  File "/usr/lib/resetter/Resetter.py", line 30, in __init__
    self.d_env = Settings()
  File "/usr/lib/resetter/SetEnvironment.py", line 27, in __init__
    self.checkForUpdate()
  File "/usr/lib/resetter/SetEnvironment.py", line 123, in checkForUpdate
    if site_version > current_version:
  File "/usr/lib/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'
```

No output to logs

**Comment by gaining** [comment]
GitHub changed the way the tags are shown on the site which ended up breaking the update checker function.
Haven't had time to code any open source projects lately. I don't think I'll release a new version with the fix soon; However, if you want a quick fix, editing the code would be the quickest way.
open the setEnvironment.py file with `sudo xed /usr/lib/resetter/SetEnvironment.py` or whichever file editor you want to use. Comment out line 27 so it goes from       `self.checkForUpdate()` to  `#self.checkForUpdate()`
Doing that will disable to update checker funtion and it should work.

**Comment by mistyferocity43** [comment]
Thanks for the hot-fix, that got it running. Although, now it's without a manifest or user-list, darn! Haha I'll find an ISO and reset the ol' fashion way for now.

**Comment by gaining** [comment]
Not sure why it doesn't find it but manifest and userlist exists for loki 0.4.1. Just open the manifest and select it via `file > open manifest`
