### ISSUE TITLE
stuck at clean

### ISSUE THREAD

**Issue by jibraniqbal666** [gaining/Resetter#69]
could you please give me a quick fix or work
my system has removed packages and i am totally stuck because clean needs to pass to reinstall packages 

*Issue title
stuck at clean

*Linux Distro and version
elementry loki 0.4.1

*Version of Resetter
2.2,3

*Description of Issue
i am stuck at clean

*this what my terminal said

Selecting previously unselected package foomatic-filters.
(Reading database ... 300751 files and directories currently installed.)
Preparing to unpack .../foomatic-filters_4.0.17-8_amd64.deb ...
Unpacking foomatic-filters (4.0.17-8) ...
Selecting previously unselected package libpaps0.
Preparing to unpack .../libpaps0_0.6.8-7ubuntu1_amd64.deb ...
Unpacking libpaps0 (0.6.8-7ubuntu1) ...
Selecting previously unselected package paps.
Preparing to unpack .../paps_0.6.8-7ubuntu1_amd64.deb ...
Unpacking paps (0.6.8-7ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up foomatic-filters (4.0.17-8) ...
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap", at /usr/lib/x86_64-linux-gnu/perl5/5.22/Gtk2.pm line 126.

Creating config file /etc/foomatic/filter.conf with new version
Setting up libpaps0 (0.6.8-7ubuntu1) ...
Setting up paps (0.6.8-7ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Finished

**Comment by gaining** [comment]
Try running the following:

sudo apt update;
sudo dpkg --configure -a;
sudo apt install -fy;
sudo apt-get autoremove -y;
sudo apt-get clean;
