### ISSUE TITLE
 impossible to start resetter

### ISSUE THREAD

**Issue by kisamexzero** [gaining/Resetter#70]
*Issue title 
impossible to start resetter

*Linux Distro and version
linux mint 18.3 

*Version of Resetter
2.2.3
*Description of Issue

install everything as it says on the page but when you start the resetter it does not start, there will be some way to fix that problem in linux mint 18.3

you could guide me to make the correct installation of resetter in linux mint 18.3
*Content of log file located in /var/log/resetter/resetter.log if applicable

**Comment by gaining** [comment]
related to #67
