### ISSUE TITLE
could you add support for deepin 15.9?

### ISSUE THREAD

**Issue by chemel9** [gaining/Resetter#72]
Hi friend ,
i have a inconvenient ,  the new deepin 15.9(15.9.2), isn't supported by resetter
could you add support for deepin 15.9?

![DeepinScreenshot_Seleccionar área_20190314003943](https://user-images.githubusercontent.com/26883220/54336498-d7b66300-45f1-11e9-8481-52d0f74a6148.png)

**Comment by gaining** [comment]
Sure, I'll update when I have the time to work on it.

**Comment by gaining** [comment]
support for Deepin 15.10 is available now thanks to @acloserview
