### ISSUE TITLE
Is there a way to run Resetter at command line for a server that has no desktop?

### ISSUE THREAD

**Issue by clearhat** [gaining/Resetter#78]
Is there a way to run Resetter at command line for a server that has no desktop?

(Example: Ubuntu Server 18.04)

I would like to run Resetter without GUI, but cannot find any documentation for this. Is it possible?

**Comment by gaining** [comment]
I used to work on a different project for server versions of distros found [there](https://github.com/gaining/resetter-cli) but due to low support/lack of interest, I abandoned the project. The version here only runs on desktop versions of distros.
