### ISSUE TITLE
Running most recent version of Resetter

### ISSUE THREAD

**Issue by lukashiaa** [gaining/Resetter#81]
It reported 'Running most recent version of Resetter' and flashbacked when i run '' sudo resetter".

**Comment by chefchristopher** [comment]
I believe i have the same issue--  iether using the shortcut or the command sudo resetter gets the banner "Resetter" logo to flash on the screen, but not run the rest of the program.  I am Kali v 2019.3 with kernal 4.19.0-kali5-amd64.  Any thoughts please?

**Comment by lukashiaa** [comment]
May be you can try to use ‘timeshift' instead of 'resetter'.

**Comment by chefchristopher** [comment]
i'll give it a go later on tonight.  thanks for the tip!

**Comment by gaining** [comment]
Kali isn't on the supported list  @lukashiaa you didn't state which distro and version you that you were running?

**Comment by lukashiaa** [comment]
@gaining Thanks. I was using the ubuntu16 ,isn't it supported?

**Comment by gaining** [comment]
@lukashiaa  which ubuntu 16.** version?

**Comment by gaining** [comment]
no response
