### ISSUE TITLE
Is there a active and working CLI version of this?

### ISSUE THREAD

**Issue by TrooperAustin** [gaining/Resetter#90]
*Issue title
Is there a active and working CLI version of this?
*Linux Distro and version
Debian 10
*Version of Resetter
n/a
*Description of Issue
is there a version of this that i can use on a server that does not have a desktop?
*Content of log file located in /var/log/resetter/resetter.log if applicable
n/a

**Comment by gaining** [comment]
I was working on one but it's discontinued: https://github.com/gaining/resetter-cli
