### ISSUE TITLE
Linux image missing

### ISSUE THREAD

**Issue by ammarbajwa** [gaining/Resetter#94]
*Linux Distro and version
Ubuntu 16.04 

There was an error while custom resetting ( one of the packages could not be deleted and gave an error) and the system got stuck. When I restarted my system it gives the following error: /boot/vmlinuz.4.4.0-12-generic.efi.signed not found. 

I guess the linux image had been uninstalled or removed. Is there a way to work around this without using a usb boot drive?

**Comment by gaining** [comment]
Hello, sorry for being so late. I haven't been working on this project at all this year. I'll take a look when I have time. And yes, your remark is most likely correct. If you could somehow reinstall that package with recovery mode, it should help.

**Comment by ammarbajwa** [comment]
Okay.
